# Final PPI dataset Generation #

Generate final PPI features dataset for for the research, by using both ESM PPI features, custom features & fegs features

In [137]:
import os
import pandas as pd

## Load & Understand the Data ##

In [138]:
esm_features_path = r"C:\Users\gavvi\Desktop\Programming\GitHub\DeepLearningResearchStarship\Research Projects\Project 5 Building Model for Research Pipeline\datasets\esm_features.csv"
custom_sequence_features_path = r"C:\Users\gavvi\Desktop\Programming\GitHub\DeepLearningResearchStarship\Research Projects\Project 5 Building Model for Research Pipeline\datasets\custom_sequence_features.csv"
fegs_features_path = r"C:\Users\gavvi\Desktop\Programming\GitHub\DeepLearningResearchStarship\Research Projects\Project 5 Building Model for Research Pipeline\datasets\fegs_features.csv"

In [139]:
esm_features_df = pd.read_csv(esm_features_path)
custom_features_df = pd.read_csv(custom_sequence_features_path)
fegs_features_df = pd.read_csv(fegs_features_path)

In [140]:
fegs_features_df.head()

,1,2,3,4,5,6,7,8,9,10,...,570,571,572,573,574,575,576,577,578,uniprotID
0,0.895642,0.895587,0.898042,0.897286,0.898124,0.896576,0.896727,0.895489,0.894779,0.896419,...,0.000000,0.000000,0.000000,0.000000,0.002273,0.002273,0.00000,0.009091,0.000000,O75530
1,0.896900,0.894494,0.894688,0.897542,0.896787,0.895580,0.900469,0.899940,0.899192,0.895858,...,0.000000,0.000000,0.000000,0.000000,0.008772,0.000000,0.00000,0.000000,0.008772,P14174
2,0.900445,0.900906,0.900568,0.895229,0.899439,0.895471,0.901190,0.894841,0.898744,0.897183,...,0.001280,0.001280,0.000000,0.001280,0.003841,0.001280,0.00128,0.000000,0.002561,P75800
3,0.898060,0.897387,0.898380,0.895475,0.896130,0.897061,0.900622,0.896395,0.898576,0.896652,...,0.001984,0.001984,0.003968,0.001984,0.005952,0.001984,0.00000,0.000000,0.001984,P37231
4,0.896231,0.895847,0.895433,0.897055,0.896401,0.899370,0.921128,0.903281,0.897424,0.897649,...,0.007407,0.000000,0.000000,0.000000,0.000000,0.007407,0.00000,0.000000,0.000000,Q16695

In [141]:
esm_features_df.head()

,UniProt_ID,Feature_0,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,...,Feature_1270,Feature_1271,Feature_1272,Feature_1273,Feature_1274,Feature_1275,Feature_1276,Feature_1277,Feature_1278,Feature_1279
0,P62942,-0.026952,-0.074381,-0.016920,-0.019834,-0.090881,-0.031264,0.065873,-0.187179,-0.018937,...,-0.018206,-0.069835,-0.072698,-0.030787,-0.012625,-0.007614,0.113761,-0.150559,-0.016927,0.137180
1,P20701,0.040105,-0.070884,-0.070652,0.082903,-0.069309,-0.074540,0.070683,0.027845,0.027884,...,0.013739,0.025413,-0.184884,0.035220,-0.037794,-0.026719,0.093608,-0.122195,-0.045078,0.117260
2,Q86Y26,0.054524,-0.115523,0.026532,0.095069,0.008715,-0.072173,0.086560,0.138818,0.154544,...,0.006488,0.084088,-0.214137,-0.006725,-0.007800,0.000843,-0.025581,-0.060492,0.154156,0.018686
3,P11474,-0.054691,-0.002792,0.067359,0.016837,-0.025287,-0.014902,0.017887,0.019004,0.087045,...,0.065262,0.028130,-0.122820,0.013742,-0.011002,-0.110906,0.023230,-0.066437,0.032996,0.082307
4,P69718,0.037008,-0.051344,-0.056333,0.178936,-0.123832,-0.081923,0.230527,-0.090900,-0.067449,...,0.096199,-0.035039,-0.081925,0.153083,0.089522,-0.109143,0.002961,-0.155136,0.071515,0.062912

In [142]:
custom_features_df.head()

,0,1,2,3,4,5,6,7,8,9,...,4691,4692,4693,4694,4695,4696,4697,4698,4699,4700
0,441.0,0.054422,0.029478,0.083900,0.047619,0.031746,0.056689,0.034014,0.061224,0.072562,...,-239.0,-960.0,-559.0,-490.0,166.88,-100.24,-46.57,-77.74,97.28,O75530
1,115.0,0.095652,0.026087,0.034783,0.026087,0.034783,0.078261,0.017391,0.052174,0.026087,...,-65.0,-267.0,-139.0,-94.0,-9.69,-67.58,-4.78,-34.60,38.68,P14174
2,782.0,0.066496,0.015345,0.058824,0.076726,0.058824,0.044757,0.016624,0.106138,0.062660,...,-533.0,-1793.0,-824.0,-558.0,-69.90,-224.31,-270.52,-224.78,197.88,P75800
3,505.0,0.053465,0.019802,0.071287,0.069307,0.053465,0.041584,0.027723,0.069307,0.077228,...,-285.0,-1199.0,-583.0,-430.0,29.50,-161.26,-119.02,-129.89,127.17,P37231
4,136.0,0.110294,0.014706,0.029412,0.051471,0.029412,0.051471,0.014706,0.051471,0.095588,...,-57.0,-339.0,-196.0,-120.0,51.70,-53.52,-105.92,2.25,33.80,Q16695

In [143]:
esm_features_df.columns

Index(['UniProt_ID', 'Feature_0', 'Feature_1', 'Feature_2', 'Feature_3',
       'Feature_4', 'Feature_5', 'Feature_6', 'Feature_7', 'Feature_8',
       ...
       'Feature_1270', 'Feature_1271', 'Feature_1272', 'Feature_1273',
       'Feature_1274', 'Feature_1275', 'Feature_1276', 'Feature_1277',
       'Feature_1278', 'Feature_1279'],
      dtype='object', length=1281)

In [144]:
custom_features_df.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '4691', '4692', '4693', '4694', '4695', '4696', '4697', '4698', '4699',
       '4700'],
      dtype='object', length=4701)

In [145]:
fegs_features_df.columns

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       ...
       '570', '571', '572', '573', '574', '575', '576', '577', '578',
       'uniprotID'],
      dtype='object', length=579)

In [146]:
custom_features_df[['4700']].head()

     4700
0  O75530
1  P14174
2  P75800
3  P37231
4  Q16695

In [147]:
# Convert uniprots column name & make it the first column in the data frame
custom_features_df.rename(columns={'4700': 'UniProt_ID'}, inplace=True)
fegs_features_df.rename(columns={'uniprotID':'UniProt_ID'}, inplace=True)

cols = ['UniProt_ID'] + [col for col in custom_features_df if col != 'UniProt_ID']
custom_features_df = custom_features_df[cols]

cols = ['UniProt_ID'] + [col for col in fegs_features_df if col != 'UniProt_ID']
fegs_features_df = fegs_features_df[cols]

In [148]:
custom_features_df.head()

,UniProt_ID,0,1,2,3,4,5,6,7,8,...,4690,4691,4692,4693,4694,4695,4696,4697,4698,4699
0,O75530,441.0,0.054422,0.029478,0.083900,0.047619,0.031746,0.056689,0.034014,0.061224,...,-110.0,-239.0,-960.0,-559.0,-490.0,166.88,-100.24,-46.57,-77.74,97.28
1,P14174,115.0,0.095652,0.026087,0.034783,0.026087,0.034783,0.078261,0.017391,0.052174,...,-30.0,-65.0,-267.0,-139.0,-94.0,-9.69,-67.58,-4.78,-34.60,38.68
2,P75800,782.0,0.066496,0.015345,0.058824,0.076726,0.058824,0.044757,0.016624,0.106138,...,-371.0,-533.0,-1793.0,-824.0,-558.0,-69.90,-224.31,-270.52,-224.78,197.88
3,P37231,505.0,0.053465,0.019802,0.071287,0.069307,0.053465,0.041584,0.027723,0.069307,...,-175.0,-285.0,-1199.0,-583.0,-430.0,29.50,-161.26,-119.02,-129.89,127.17
4,Q16695,136.0,0.110294,0.014706,0.029412,0.051471,0.029412,0.051471,0.014706,0.051471,...,-48.0,-57.0,-339.0,-196.0,-120.0,51.70,-53.52,-105.92,2.25,33.80

In [149]:
custom_features_uniprots = custom_features_df[['UniProt_ID']]
esm_features_uniprots = esm_features_df[['UniProt_ID']]
fegs_features_uniprots = fegs_features_df[['UniProt_ID']]

In [150]:
custom_features_uniprots.shape , fegs_features_uniprots.shape, esm_features_uniprots.shape,

((333, 1), (334, 1), (292, 1))

In [151]:
unique_custom_uniprots = custom_features_uniprots['UniProt_ID'].nunique()
unique_esm_uniprots = esm_features_uniprots['UniProt_ID'].nunique()
unique_fegs_uniprots = fegs_features_uniprots['UniProt_ID'].nunique()

print(f"Number of unique UniProt IDs in custom_features_df: {unique_custom_uniprots}")
print(f"Number of unique UniProt IDs in fegs_features_df: {unique_fegs_uniprots}")
print(f"Number of unique UniProt IDs in esm_features_df: {unique_esm_uniprots}")

Number of unique UniProt IDs in custom_features_df: 329
Number of unique UniProt IDs in fegs_features_df: 330
Number of unique UniProt IDs in esm_features_df: 292

In [152]:
final_ds_path = r"C:\Users\gavvi\Desktop\Programming\GitHub\DeepLearningResearchStarship\Research Projects\Project 5 Building Model for Research Pipeline\datasets\final_dataset_2_0.75.csv"
final_df = pd.read_csv(final_ds_path)

## Scale & Merge all PPI feature datasets ##

In [153]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()


# Scale the values of all PPI features data frames by standard scaler
columns_to_scale = custom_features_df.columns.difference(['UniProt_ID'])
custom_features_df[columns_to_scale] = scaler.fit_transform(custom_features_df[columns_to_scale])

columns_to_scale = fegs_features_df.columns.difference(['UniProt_ID'])
fegs_features_df[columns_to_scale] = scaler.fit_transform(fegs_features_df[columns_to_scale])

columns_to_scale = esm_features_df.columns.difference(['UniProt_ID'])
esm_features_df[columns_to_scale] = scaler.fit_transform(esm_features_df[columns_to_scale])

In [154]:
custom_features_df.head()

,UniProt_ID,0,1,2,3,4,5,6,7,8,...,4690,4691,4692,4693,4694,4695,4696,4697,4698,4699
0,O75530,-0.453878,-0.595435,0.318021,2.071079,-1.194795,-0.271327,-0.453332,0.978000,0.985672,...,0.307128,0.408311,0.500234,0.475209,0.340958,-0.126466,0.801008,0.614232,0.530812,-0.482979
1,P14174,-1.040436,1.206415,0.132703,-1.082878,-2.212747,-0.057994,0.482222,-0.653199,0.459969,...,0.806937,1.055104,0.998036,0.985859,0.985808,-0.688051,0.929651,0.898549,0.801996,-0.765637
2,P75800,0.159669,-0.067760,-0.454246,0.460846,0.181283,1.630987,-0.970835,-0.728493,3.594479,...,-1.323500,-0.684545,-0.098135,0.153013,0.230227,-0.879550,0.312314,-0.909406,-0.393500,0.002266
3,P37231,-0.338725,-0.637232,-0.210722,1.261162,-0.169477,1.254551,-1.108442,0.360661,1.455141,...,-0.098967,0.237320,0.328553,0.446029,0.438663,-0.563406,0.560659,0.121320,0.202990,-0.338804
4,Q16695,-1.002652,1.846296,-0.489184,-1.427753,-1.012709,-0.435320,-0.679669,-0.916728,0.419117,...,0.694480,1.084841,0.946316,0.916557,0.943469,-0.492799,0.985032,0.210446,1.033640,-0.789176

In [155]:
fegs_features_df.head()

,UniProt_ID,1,2,3,4,5,6,7,8,9,...,569,570,571,572,573,574,575,576,577,578
0,O75530,-0.690323,-0.670513,-0.380735,-0.325120,0.109350,-0.584750,-1.366016,-0.875028,-1.283051,...,-0.142930,-1.048832,-0.718648,-0.846315,-1.037752,-0.648007,-0.413549,-0.424312,4.015992,-1.169177
1,P14174,-0.193412,-1.059180,-1.278588,-0.263681,-0.386063,-0.915209,-0.668021,0.093001,0.177767,...,-1.267206,-1.048832,-0.718648,-0.846315,-1.037752,1.233715,-1.068580,-0.424312,-0.713930,1.191788
2,P75800,1.207496,1.220249,0.295393,-0.819098,0.596749,-0.951575,-0.533480,-1.015802,0.029285,...,0.949676,-0.652408,-0.109482,-0.846315,-0.685379,-0.193877,-0.699549,0.591251,-0.713930,-0.479932
3,P37231,0.265186,-0.030587,-0.290296,-0.760123,-0.629531,-0.424159,-0.639366,-0.677950,-0.026118,...,-1.267206,-0.434532,0.225318,0.759300,-0.491714,0.417368,-0.496728,-0.424312,-0.713930,-0.635149
4,Q16695,-0.457738,-0.578066,-1.078967,-0.380653,-0.529394,0.342126,3.185610,0.819713,-0.407514,...,0.564947,1.244555,-0.718648,-0.846315,-1.037752,-1.306033,1.066336,-0.424312,-0.713930,-1.169177

In [156]:
esm_features_df.head()

,UniProt_ID,Feature_0,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,...,Feature_1270,Feature_1271,Feature_1272,Feature_1273,Feature_1274,Feature_1275,Feature_1276,Feature_1277,Feature_1278,Feature_1279
0,P62942,-1.232137,-0.407230,-0.043823,-1.393333,-0.471680,0.617138,-0.349967,-1.965319,-0.219609,...,-0.763119,-1.350688,0.764230,-1.202063,-0.424401,0.861400,1.671297,-0.560356,-0.679301,0.781521
1,P20701,0.808479,-0.335420,-1.257514,0.331975,-0.131128,-0.504292,-0.278562,0.405159,0.522920,...,-0.226874,0.928600,-0.980412,0.215275,-1.073493,0.555952,1.293377,-0.148521,-1.146379,0.462027
2,Q86Y26,1.247254,-1.252035,0.937655,0.536282,1.100609,-0.442955,-0.042903,1.628557,2.531630,...,-0.348597,2.332675,-1.435320,-0.685403,-0.299964,0.996614,-0.941635,0.747357,2.159298,-1.118946
3,P11474,-2.076272,1.062794,1.859841,-0.777508,0.563826,1.041152,-1.062229,0.307698,1.461156,...,0.638002,0.993605,-0.015240,-0.245922,-0.382554,-0.790018,-0.026337,0.661032,0.149024,-0.098554
4,P69718,0.714242,0.065832,-0.934076,1.944716,-0.991876,-0.695638,2.094043,-0.903922,-0.988961,...,1.157316,-0.518023,0.620736,2.746097,2.209911,-0.761841,-0.406426,-0.626814,0.788130,-0.409633

In [157]:
combined_uniprots = pd.concat([final_df['uniprot_id1'], final_df['uniprot_id2']])
unique_uniprots = combined_uniprots.nunique()

print(f"Number of unique UniProt IDs in both in final_dataset_2_0.75: {unique_uniprots}")

Number of unique UniProt IDs in both in final_dataset_2_0.75: 296

In [158]:
merged_uniprots = pd.merge(custom_features_df, esm_features_df, on='UniProt_ID', how='inner')
merged_uniprots = pd.merge(fegs_features_df, merged_uniprots, on='UniProt_ID', how='inner')

In [159]:
merged_uniprots['UniProt_ID'].nunique()

291

There are one missing UniProt_ID in 'merged_df' the was in ESM PPI features data frame. We'll find him, add him and his coressponding features from ESM PPI feature dataset to the merged data frame, and for now, we'll fill the missing columns values with zeros.

In [160]:
missing_uniprot_id = esm_features_df[~esm_features_df['UniProt_ID'].isin(merged_uniprots['UniProt_ID'])]

print("Missing UniProt_ID and its values from esm_features_df:\n")
print(missing_uniprot_id['UniProt_ID'])

Missing UniProt_ID and its values from esm_features_df:

149    C5J4T0
Name: UniProt_ID, dtype: object

In [161]:
new_row_data = {col: missing_uniprot_id.iloc[0][col] for col in missing_uniprot_id.columns}

for col in merged_uniprots.columns:
    if col not in new_row_data:
        new_row_data[col] = 0

new_row_df = pd.DataFrame([new_row_data])

In [162]:
new_row_df

,UniProt_ID,Feature_0,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,...,4690,4691,4692,4693,4694,4695,4696,4697,4698,4699
0,C5J4T0,1.298412,-0.35987,-1.288287,-1.223119,0.278517,-3.072404,-1.519044,0.108695,0.188554,...,0,0,0,0,0,0,0,0,0,0

In [163]:
merged_uniprots = pd.concat([merged_uniprots, new_row_df], ignore_index=True)

In [164]:
merged_uniprots['UniProt_ID'].nunique()

292

In [166]:
merged_uniprots.head()

,UniProt_ID,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,...,Feature_1270,Feature_1271,Feature_1272,Feature_1273,Feature_1274,Feature_1275,Feature_1276,Feature_1277,Feature_1278,Feature_1279
0,P14174,-0.193412,-1.059180,-1.278588,-0.263681,-0.386063,-0.915209,-0.668021,0.093001,0.177767,...,-0.638152,-0.473444,0.745981,-0.451562,-2.777358,-1.538830,0.639083,-2.094676,0.286921,2.930260
1,P37231,0.265186,-0.030587,-0.290296,-0.760123,-0.629531,-0.424159,-0.639366,-0.677950,-0.026118,...,2.327607,0.024786,0.870385,-0.229874,-0.297020,1.548407,0.651663,-0.201770,-0.571092,-0.550890
2,Q16695,-0.457738,-0.578066,-1.078967,-0.380653,-0.529394,0.342126,3.185610,0.819713,-0.407514,...,-1.060836,-0.302551,1.048564,0.980907,-0.509805,0.867835,0.441861,1.236238,-1.328273,-1.193699
3,Q86Y26,-0.302110,-0.103794,0.235311,0.308580,-0.420244,0.325662,0.747183,1.307642,1.054643,...,-0.348597,2.332675,-1.435320,-0.685403,-0.299964,0.996614,-0.941635,0.747357,2.159298,-1.118946
4,Q14469,1.493006,0.636802,-0.305837,1.480889,0.848687,-0.507851,0.909075,1.592308,1.030355,...,0.658024,1.259431,1.463462,0.111468,1.053912,-0.894036,-0.583210,-0.825652,0.860949,-1.388991

Next, we'll change all features columns names to match the next pattern -> `Feature_i` , where i goes from 1 to the number of total PPI features

In [167]:
current_columns = merged_uniprots.columns
new_column_names = ['UniProt_ID'] + [f'Feature_{i+1}' for i in range(len(current_columns) - 1)]

# Create a dictionary mapping current column names to new names
rename_dict = dict(zip(current_columns, new_column_names))

merged_uniprots.rename(columns=rename_dict, inplace=True)

In [168]:
merged_uniprots

,UniProt_ID,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,...,Feature_6549,Feature_6550,Feature_6551,Feature_6552,Feature_6553,Feature_6554,Feature_6555,Feature_6556,Feature_6557,Feature_6558
0,P14174,-0.193412,-1.059180,-1.278588,-0.263681,-0.386063,-0.915209,-0.668021,0.093001,0.177767,...,-0.638152,-0.473444,0.745981,-0.451562,-2.777358,-1.538830,0.639083,-2.094676,0.286921,2.930260
1,P37231,0.265186,-0.030587,-0.290296,-0.760123,-0.629531,-0.424159,-0.639366,-0.677950,-0.026118,...,2.327607,0.024786,0.870385,-0.229874,-0.297020,1.548407,0.651663,-0.201770,-0.571092,-0.550890
2,Q16695,-0.457738,-0.578066,-1.078967,-0.380653,-0.529394,0.342126,3.185610,0.819713,-0.407514,...,-1.060836,-0.302551,1.048564,0.980907,-0.509805,0.867835,0.441861,1.236238,-1.328273,-1.193699
3,Q86Y26,-0.302110,-0.103794,0.235311,0.308580,-0.420244,0.325662,0.747183,1.307642,1.054643,...,-0.348597,2.332675,-1.435320,-0.685403,-0.299964,0.996614,-0.941635,0.747357,2.159298,-1.118946
4,Q14469,1.493006,0.636802,-0.305837,1.480889,0.848687,-0.507851,0.909075,1.592308,1.030355,...,0.658024,1.259431,1.463462,0.111468,1.053912,-0.894036,-0.583210,-0.825652,0.860949,-1.388991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,P26010,-0.875354,-0.695519,-1.022359,-0.159833,0.005862,1.067217,-0.719335,-0.310583,-0.357420,...,-1.051942,1.570161,-1.201297,0.307353,-0.817249,-0.680510,0.896902,0.240313,-0.228701,-0.492168
300,P15923,2.171134,3.002980,1.039180,4.124208,0.819659,2.015659,-0.284286,3.506398,-1.011191,...,-0.208972,-0.671560,-1.350531,0.191476,0.778141,-2.407970,-1.797525,-0.208179,3.606452,-0.801161
301,P02638,5.158540,5.280304,0.476600,1.565221,3.485384,2.949100,0.355090,-0.055455,1.845577,...,0.456594,-0.776802,0.985265,1.507724,-0.584367,-0.020678,-1.135115,-0.892691,-0.388317,0.923502
302,Q9TUN4,-0.736741,-0.633878,-1.094852,-0.253876,-1.006826,-0.704008,-0.580686,-0.243270,0.020465,...,-1.023290,0.160326,-1.095301,0.203843,-1.054148,-0.292396,1.932162,0.014309,-0.624819,0.316326
303,C5J4T0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.438602,0.090468,0.204217,-2.960944,0.998519,1.313901,1.609496,0.922661,-1.638882,0.102766

In [170]:
merged_uniprots.to_csv(r"C:\Users\gavvi\Desktop\Programming\GitHub\DeepLearningResearchStarship\Research Projects\Project 5 Building Model for Research Pipeline\datasets\merged_ppi_features.csv", index=False)